Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: cogniteAuth.LambdaHandler
      CodeUri: C:\Projetos\Github\hackathon-fiap-cognito-auth\HackathonFiapCognitoAuth
      Runtime: java21
      Architectures:
        - x86_64
      Environment:
        Variables:
          COGNITO_CLIENT_ID: 76sc7h5cv5nqb2onaav82522nb